name: Backend CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'mvnw'
      - 'mvnw.cmd'
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'mvnw'
      - 'mvnw.cmd'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v7

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test